<%
  encoding = 'unicode'
  if ENV['OSEM_DB_ADAPTER'] == 'mysql2'
    encoding = 'utf8'
  end
%>


default: &default
  adapter: <%= ENV['OSEM_DB_ADAPTER'] || 'mysql2' %>
  encoding: <%= encoding %>
  host: <%= ENV['OSEM_DB_HOST'] || 'localhost' %>
  port: <%= ENV['OSEM_DB_PORT'] || '3306'  %>
  username: <%= ENV['OSEM_DB_USER'] || 'root' %>
  password: <%= ENV['OSEM_DB_PASSWORD'] || 'password' %>
  database: <%= ENV['OSEM_DB_NAME'] || 'osem_development' %>
  pool: 5
  timeout: 50000

development:
  <<: *default
  host: localhost
  database: osem_development

# Warning: The database defined as "test" will be erased and
# re-generated when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  host: localhost
  database: osem_test

production:
  <<: *default
