production:
  adapter: mysql2
  encoding: utf8
  database: osem
  username: ecs_root
  password: nig2utaw

development:
  adapter: mysql2
  encoding: utf8
  database: osem_testing
  username: ecs_root
  password: nig2utaw
